=
## Worksheet 0 —  Python and NumPy for Deep Learning

## Exercise on Functions

### Task 1 — Unit Converter

In [1]:
def convert_units(value, conversion_type):
    """
    Converts a value between different units of measurement.

    Parameters:
        value (float): The numeric value to convert.
        conversion_type (str): The type of conversion to perform.
            Options: 'm_to_ft', 'ft_to_m', 'kg_to_lbs', 'lbs_to_kg', 'l_to_gal', 'gal_to_l'

    Returns:
        float: The converted value.
    """
    conversions = {
        'm_to_ft'   : lambda v: v * 3.28084,
        'ft_to_m'   : lambda v: v / 3.28084,
        'kg_to_lbs' : lambda v: v * 2.20462,
        'lbs_to_kg' : lambda v: v / 2.20462,
        'l_to_gal'  : lambda v: v * 0.264172,
        'gal_to_l'  : lambda v: v / 0.264172,
    }

    if conversion_type not in conversions:
        raise ValueError(f"Unsupported conversion type: '{conversion_type}'")

    return conversions[conversion_type](value)


def unit_converter():
    """
    Interactive unit converter. Prompts the user to select a conversion
    category and input a value, then displays the result.
    """
    print("Unit Converter")
    print("1. Length   (meters <-> feet)")
    print("2. Weight   (kilograms <-> pounds)")
    print("3. Volume   (liters <-> gallons)")

    category = input("\nChoose category (1/2/3): ").strip()

    options = {
        '1': [('1a', 'Meters to Feet',     'm_to_ft'),
              ('1b', 'Feet to Meters',     'ft_to_m')],
        '2': [('2a', 'Kilograms to Pounds','kg_to_lbs'),
              ('2b', 'Pounds to Kilograms','lbs_to_kg')],
        '3': [('3a', 'Liters to Gallons',  'l_to_gal'),
              ('3b', 'Gallons to Liters',  'gal_to_l')],
    }

    if category not in options:
        print("Invalid category.")
        return

    for key, label, _ in options[category]:
        print(f"  {key}. {label}")

    sub = input("Choose conversion: ").strip()
    conversion_map = {key: ctype for key, _, ctype in options[category]}

    if sub not in conversion_map:
        print("Invalid choice.")
        return

    try:
        value = float(input("Enter value: "))
        result = convert_units(value, conversion_map[sub])
        print(f"Result: {result:.4f}")
    except ValueError as e:
        print(f"Error: {e}")


unit_converter()

Unit Converter
1. Length   (meters <-> feet)
2. Weight   (kilograms <-> pounds)
3. Volume   (liters <-> gallons)

Choose category (1/2/3): 3
  3a. Liters to Gallons
  3b. Gallons to Liters
Choose conversion: 3a
Enter value: 77
Result: 20.3412


### Task 2 — List Statistics

In [2]:
def compute_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The sum of all elements.
    """
    if not numbers:
        raise ValueError("List is empty.")
    total = 0
    for n in numbers:
        total += n
    return total


def compute_average(numbers):
    """
    Returns the average of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The average of all elements.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return compute_sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Returns the maximum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The largest element.
    """
    if not numbers:
        raise ValueError("List is empty.")
    result = numbers[0]
    for n in numbers:
        if n > result:
            result = n
    return result


def compute_minimum(numbers):
    """
    Returns the minimum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The smallest element.
    """
    if not numbers:
        raise ValueError("List is empty.")
    result = numbers[0]
    for n in numbers:
        if n < result:
            result = n
    return result


def list_statistics():
    """
    Interactive program for performing mathematical operations on a user-provided list.
    """
    print("List Operations")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("\nChoose operation (1/2/3/4): ").strip()
    operations = {'1': compute_sum, '2': compute_average, '3': compute_maximum, '4': compute_minimum}

    if choice not in operations:
        print("Invalid choice.")
        return

    try:
        raw = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in raw.split()]
        result = operations[choice](numbers)
        print(f"Result: {result}")
    except ValueError as e:
        print(f"Error: {e}")


list_statistics()

List Operations
1. Sum
2. Average
3. Maximum
4. Minimum

Choose operation (1/2/3/4): 3
Enter numbers separated by spaces: 7 9 8
Result: 9.0


## Exercise on List Manipulation

In [3]:
# 1. Extract every other element starting from the first
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))  # [1, 3, 5]

[1, 3, 5]


In [4]:
# 2. Return a sublist from start to end (inclusive)
def get_sublist(lst, start, end):
    return lst[start:end + 1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))  # [3, 4, 5]

[3, 4, 5]


In [5]:
# 3. Reverse a list using slicing
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))  # [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]


In [6]:
# 4. Remove the first and last elements
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))  # [2, 3, 4]

[2, 3, 4]


In [7]:
# 5. Get first n elements
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))  # [1, 2, 3]

[1, 2, 3]


In [8]:
# 6. Get last n elements
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))  # [4, 5]

[4, 5]


In [9]:
# 7. Extract every second element starting from second-to-last, moving backward
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))  # [5, 3, 1]

[5, 3, 1]


## Exercise on Nested Lists

In [10]:
# 1. Flatten a nested list (one level deep)
def flatten(lst):
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result

print(flatten([[1, 2], [3, 4], [5]]))  # [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


In [11]:
# 2. Access a nested element given a list of indices
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))  # 6

6


In [12]:
# 3. Sum all elements in a nested list (any depth)
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # 21

21


In [13]:
# 4. Remove all occurrences of a specific element from a nested list
def remove_element(lst, elem):
    result = []
    for sublist in lst:
        result.append([x for x in sublist if x != elem])
    return result

print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # [[1], [3], [4, 5]]

[[1], [3], [4, 5]]


In [14]:
# 5. Find the maximum element in a nested list (any depth)
def find_max(lst):
    values = []
    for item in lst:
        if isinstance(item, list):
            values.append(find_max(item))
        else:
            values.append(item)
    return max(values)

print(find_max([[1, 2], [3, [4, 5]], 6]))  # 6

6


In [15]:
# 6. Count occurrences of an element in a nested list
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # 3

3


In [16]:
# 7. Deep flatten (any depth)
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
# 8. Average of all elements in a nested list
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print(average_nested([[1, 2], [3, 4], [5, 6]]))  # 3.5

3.5


## NumPy — Basic Vector and Matrix Operations

In [18]:
import numpy as np

### Problem 1 — Array Creation

In [19]:
# 1. Empty array of size 2x2
empty_arr = np.empty((2, 2))
print('Empty 2x2:\n', empty_arr)

Empty 2x2:
 [[2.64567624e-315 0.00000000e+000]
 [2.33419537e-312 2.42092166e-322]]


In [20]:
# 2. All-ones array of size 4x2
ones_arr = np.ones((4, 2))
print('Ones 4x2:\n', ones_arr)

Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
# 3. Array filled with a specific value
filled_arr = np.full((3, 3), 7)
print('Filled with 7 (3x3):\n', filled_arr)

Filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [22]:
# 4. Zeros with same shape as an existing array
existing = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like = np.zeros_like(existing)
print('Zeros like existing:\n', zeros_like)

Zeros like existing:
 [[0 0 0]
 [0 0 0]]


In [23]:
# 5. Ones with same shape as an existing array
ones_like = np.ones_like(existing)
print('Ones like existing:\n', ones_like)

Ones like existing:
 [[1 1 1]
 [1 1 1]]


In [24]:
# 6. Convert list to NumPy array
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print('Array from list:', arr_from_list)

Array from list: [1 2 3 4]


### Problem 2 — Array Manipulation

In [25]:
# 1. Array with values from 10 to 49
arr = np.arange(10, 50)
print('Range 10-49:', arr)

Range 10-49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [28]:
# 2. 3x3 matrix with values 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print('3x3 matrix (0-8):\n', matrix_3x3)

3x3 matrix (0-8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
# 3. 3x3 identity matrix
identity = np.eye(3)
print('Identity matrix:\n', identity)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
# 4. Random array of size 30 and its mean
rand_arr = np.random.random(30)
print('Random array:', rand_arr)
print('Mean:', rand_arr.mean())

Random array: [0.52751089 0.47179443 0.84915481 0.5210644  0.36034381 0.87222544
 0.98169027 0.78035902 0.16637604 0.23286791 0.0782469  0.1881958
 0.35776447 0.62281651 0.58088473 0.03528975 0.79007689 0.67072979
 0.96453527 0.55376506 0.28031017 0.46276001 0.97652089 0.87758854
 0.37656092 0.44867244 0.77619601 0.66653345 0.30594744 0.05691696]
Mean: 0.5277899672393622


In [31]:
# 5. 10x10 random array, min and max
rand_10x10 = np.random.random((10, 10))
print('Min:', rand_10x10.min())
print('Max:', rand_10x10.max())

Min: 0.00022893755994168874
Max: 0.9919209472820281


In [32]:
# 6. Zero array of size 10, replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print('Array with 5th element = 1:', zero_arr)

Array with 5th element = 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [33]:
# 7. Reverse an array
arr_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr_to_reverse[::-1]
print('Reversed:', reversed_arr)

Reversed: [0 4 0 0 2 1]


In [34]:
# 8. 2D array with 1 on the border and 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print('Border array:\n', border_arr)

Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print('Checkerboard:\n', checkerboard)

Checkerboard:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem 3 — Array Operations

In [36]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Addition
print('x + y:\n', x + y)

x + y:
 [[ 6  8]
 [10 13]]


In [37]:
# 2. Subtraction
print('x - y:\n', x - y)

x - y:
 [[-4 -4]
 [-4 -3]]


In [38]:
# 3. Multiply by a scalar
scalar = 3
print(f'x * {scalar}:\n', x * scalar)

x * 3:
 [[ 3  6]
 [ 9 15]]


In [39]:
# 4. Square each element
print('x squared:\n', np.square(x))

x squared:
 [[ 1  4]
 [ 9 25]]


In [40]:
# 5. Dot products
print('v . w     :', np.dot(v, w))
print('x . v     :', np.dot(x, v))
print('x . y     :\n', np.dot(x, y))

v . w     : 219
x . v     : [29 77]
x . y     :
 [[19 22]
 [50 58]]


In [41]:
# 6. Concatenate x and y along rows (axis=0), v and w along columns
concat_rows = np.concatenate((x, y), axis=0)
concat_cols = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print('x and y concatenated (rows):\n', concat_rows)
print('v and w concatenated (columns):\n', concat_cols)

x and y concatenated (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w concatenated (columns):
 [[ 9 11]
 [10 12]]


In [42]:
# 7. Try to concatenate x and v — observe the error
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print(f'Error: {e}')

# Explanation:
# x has shape (2, 2) and v has shape (2,) — they have different numbers of dimensions.
# np.concatenate requires all arrays to have the same number of dimensions.
# v needs to be reshaped (e.g., to (1, 2) or (2, 1)) before concatenation.

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


### Problem 4 — Matrix Operations

In [43]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A_inverse = Identity
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print('A * A_inv (should be I):\n', np.round(identity_check, decimals=10))

A * A_inv (should be I):
 [[1. 0.]
 [0. 1.]]


In [44]:
# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print('AB:\n', AB)
print('BA:\n', BA)
print('AB == BA:', np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA: False


In [45]:
# 3. Prove (AB)^T = B^T * A^T
lhs = np.dot(A, B).T
rhs = np.dot(B.T, A.T)
print('(AB)^T:\n', lhs)
print('B^T * A^T:\n', rhs)
print('Equal:', np.array_equal(lhs, rhs))

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Equal: True


In [46]:
# Solve system of linear equations:
# 2x - 3y + z  = -1
# x  - y  + 2z = -3
# 3x + y  - z  =  9

coeff_matrix = np.array([
    [2, -3,  1],
    [1, -1,  2],
    [3,  1, -1]
])
constants = np.array([-1, -3, 9])

# Using inverse method: X = A_inv * B
A_inv = np.linalg.inv(coeff_matrix)
X_inv_method = np.dot(A_inv, constants)
print('Solution using inverse method (x, y, z):', np.round(X_inv_method, 4))

Solution using inverse method (x, y, z): [ 2.  1. -2.]


In [47]:
# Using np.linalg.solve
X_solve = np.linalg.solve(coeff_matrix, constants)
print('Solution using np.linalg.solve (x, y, z):', np.round(X_solve, 4))

Solution using np.linalg.solve (x, y, z): [ 2.  1. -2.]


## Experiment — How Fast is NumPy?

In [48]:
import time

size = 1_000_000
a_list = list(range(size))
b_list = list(range(size))
a_np   = np.array(a_list)
b_np   = np.array(b_list)

# 1. Element-wise Addition
start = time.time()
result = [a_list[i] + b_list[i] for i in range(size)]
print(f'Addition   — Python list : {time.time() - start:.5f}s')

start = time.time()
result = a_np + b_np
print(f'Addition   — NumPy       : {time.time() - start:.5f}s')

Addition   — Python list : 0.18199s
Addition   — NumPy       : 0.02627s


In [49]:
# 2. Element-wise Multiplication
start = time.time()
result = [a_list[i] * b_list[i] for i in range(size)]
print(f'Multiply   — Python list : {time.time() - start:.5f}s')

start = time.time()
result = a_np * b_np
print(f'Multiply   — NumPy       : {time.time() - start:.5f}s')

Multiply   — Python list : 0.10634s
Multiply   — NumPy       : 0.02222s


In [50]:
# 3. Dot Product
start = time.time()
result = sum(a_list[i] * b_list[i] for i in range(size))
print(f'Dot product — Python list : {time.time() - start:.5f}s')

start = time.time()
result = np.dot(a_np, b_np)
print(f'Dot product — NumPy       : {time.time() - start:.5f}s')

Dot product — Python list : 0.10251s
Dot product — NumPy       : 0.00183s


In [51]:
# 4. Matrix Multiplication (1000x1000)
mat_size = 1000
mat_a_list = [[1.0] * mat_size for _ in range(mat_size)]
mat_b_list = [[1.0] * mat_size for _ in range(mat_size)]
mat_a_np   = np.ones((mat_size, mat_size))
mat_b_np   = np.ones((mat_size, mat_size))

start = time.time()
result = [[sum(mat_a_list[i][k] * mat_b_list[k][j] for k in range(mat_size))
           for j in range(mat_size)] for i in range(mat_size)]
print(f'Matrix multiply — Python list : {time.time() - start:.5f}s')

start = time.time()
result = np.dot(mat_a_np, mat_b_np)
print(f'Matrix multiply — NumPy       : {time.time() - start:.5f}s')

Matrix multiply — Python list : 118.76936s
Matrix multiply — NumPy       : 0.11370s
